# services:
#   db:
#     # We're using MariaDB, which supports both amd64 and arm64 architectures
#     image: mariadb:10.6
#     command: '--default-authentication-plugin=mysql_native_password'
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     environment:
#       - MYSQL_ROOT_PASSWORD=rootpassword  # Root password for MySQL
#       - MYSQL_DATABASE=wordpress_db      # The WordPress database name
#       - MYSQL_USER=user-doa              # The user for the WordPress database
#       - MYSQL_PASSWORD=db_password       # The password for the WordPress database user
#     expose:
#       - 3306  # Expose MySQL port

#   wordpress:
#     image: wordpress:latest
#     volumes:
#       - wp_data:/var/www/html
#     ports:
#       - 8000:80  # Expose WordPress on port 80
#     restart: always
#     environment:
#       - WORDPRESS_DB_HOST=db  # Link to the db service
#       - WORDPRESS_DB_USER=user-doa  # MySQL user for WordPress to access the DB
#       - WORDPRESS_DB_PASSWORD=db_password  # Password for the MySQL user
#       - WORDPRESS_DB_NAME=wordpress_db  # The database name WordPress will use


#   wordmove:
#   tty: true
#   depends_on:
#     - wordpress
#   image: welaika/wordmove:latest  # Use this image
#   restart: on-failure:5
#   container_name: my_wordmove
#   volumes:
#     - ./config:/home  # Movefile location
#     - ./public:/var/www/html  # WordPress files
#     - ~/.ssh:/root/.ssh  # SSH keys (for production)
#     - ./Movefile:/home/Movefile  # Movefile configuration


# volumes:
#   db_data:  # Persist MySQL database data
#   wp_data:  # Persist WordPress data (themes, plugins, uploads)

services:
  db:
    # We're using MariaDB, which supports both amd64 and arm64 architectures
    image: mariadb:10.6
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # Root password for MySQL
      - MYSQL_DATABASE=wordpress_db      # The WordPress database name
      - MYSQL_USER=user-doa              # The user for the WordPress database
      - MYSQL_PASSWORD=db_password       # The password for the WordPress database user
    expose:
      - 3306  # Expose MySQL port

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 8000:80  # Expose WordPress on port 80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db  # Link to the db service
      - WORDPRESS_DB_USER=user-doa  # MySQL user for WordPress to access the DB
      - WORDPRESS_DB_PASSWORD=db_password  # Password for the MySQL user
      - WORDPRESS_DB_NAME=wordpress_db  # The database name WordPress will use

volumes:
  db_data:  # Persist MySQL database data
  wp_data:  # Persist WordPress data (themes, plugins, uploads)
