name: Deploying WordPress Site

on:
  push:
    branches:
      - staging
      # - staging-header-branch # Adjust this based on the branch you want to trigger deployment

jobs:
  deploy:
    name: Deploy WordPress
    runs-on: ubuntu-latest # Change to a different runner if needed (e.g., windows-latest)         # uses: webfactory/ssh-agent@v0.5.3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync Files to Remote Server
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: 3.24.178.18 # Remote server IP or domain
          remote-user: bitnami # SSH username on the server
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: /home/bitnami/stack/wordpress/wp-content/themes/starter-theme-sass
          ssh-port: 22
          source-path: ./starter-theme-sass/
          rsync-options: --archive --verbose --compress --human-readable --progress --delete-after --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
